#!/usr/bin/env python3
"""Generate the five-image portrait cycle for the left nice!view.

Each source is an exact 68x92 physical portrait, stored compactly below as a
zlib/base85 stream of one-byte ink values. The generator rotates each source
clockwise into LVGL's 92x68 logical layout and emits indexed one-bit assets.
"""

from __future__ import annotations

import argparse
import base64
import struct
import zlib
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
ART_C_PATH = REPO_ROOT / "config/boards/shields/keyball61_left_view/widgets/art.c"
PREVIEW_DIR = REPO_ROOT / "art/rtr_cycle"

PHYSICAL_WIDTH = 68
PHYSICAL_HEIGHT = 92
LOGICAL_WIDTH = 92
LOGICAL_HEIGHT = 68

# Order is intentional and is also the boot/deep-sleep wake cycle order.
SOURCES = (
    (
        "rtr_c2_folded_ribbon",
        "C2 Folded Ribbon",
        "c-rmP!4AVP2m?^^|3AHJr4_J^w?<nyw%co!0tpd&#hMG(xVdz_ffy-KD=1MZIFTz1ktvG}hp|$F$N<@RU$~K>zlU`_<nL0~Cq)c$tZNbmA`C=~3WYR)53iI7oMS{EQ%e@kb+C_3+J{iLS>ckKnQVM`zun^0FboK(pN72&LNo|QgiI`GU11_e2%`HD-x}}#>BzoKj5vmY_*Em0(VUC_(0F)OmyWoWgEFy`Q-(gP>k~gmv@;>N#%EUFXI8Hh#6ZMc_+sfBT9BcQp}AAsjiGU7^)stK9xu4G2!H",
    ),
    (
        "rtr_cl1_carved_monolith",
        "CL1 Carved Monolith",
        "c-rmQ!3_W)2t!fae`yymh{lt=p3P4n6|51o(zwvCjEueOT^B~y!;TF8;2E{o&!5g^j2;a06r<{~%9{@Z1H*p7uwP^q`BuJ_Z(lR~pVsbHM@_Lv4gm",
    ),
    (
        "rtr_cl3_skeleton_stack",
        "CL3 Skeleton Stack",
        "c-rmPu?+wq2n0age`yz>Axa_K4{*gNM1L)bvXhx$WV&O_Gu%tArx#uSZe+YphTPp;)N3c>=8hN)2BYFl>STCt{nza|hJ9<_+PC(t)aL-UL<PY",
    ),
    (
        "rtr_cl5_splitfield",
        "CL5 Splitfield",
        "c-rmPI|=|G5Cc)Y|D`Pj!7o_lO=&TLxEoRmM(T!S$H^Uuj@4PB!~dAS>B;ORIg;l^zHr#59IuYs-NV7bAzwJ;i+-!$>bLr>e*4#fP6NZW3Ly",
    ),
    (
        "rtr_track_totem",
        "Track Totem",
        "c-rmQi46cD2t-loziBIwBM}4mr+{Zx<LbB;u_K4{GQ^Skh6GdA@O-YtlrxmMu|~s4H*TzL6~i+<?F?P&X!P1Ilg^isXJzP~gYnF8{y8u(em3YY^cM{J3;l)ulGI-&z4gs|gZ(`lP`M13",
    ),
)


def decode_master(encoded: str) -> list[list[int]]:
    raw = zlib.decompress(base64.b85decode(encoded.encode("ascii")))
    expected = PHYSICAL_WIDTH * PHYSICAL_HEIGHT
    if len(raw) != expected or set(raw) - {0, 1}:
        raise ValueError("invalid embedded one-bit master")
    return [
        list(raw[offset : offset + PHYSICAL_WIDTH])
        for offset in range(0, expected, PHYSICAL_WIDTH)
    ]


def rotate_clockwise(master: list[list[int]]) -> list[list[int]]:
    """Rotate a physical 68x92 portrait into LVGL's 92x68 coordinates."""
    logical = [[0] * LOGICAL_WIDTH for _ in range(LOGICAL_HEIGHT)]
    for y, row in enumerate(master):
        for x, ink in enumerate(row):
            logical[x][PHYSICAL_HEIGHT - 1 - y] = ink
    return logical


def pack_lvgl_rows(logical: list[list[int]]) -> bytes:
    """Pack ink=0/background=1 indices, byte-aligned per LVGL row."""
    packed = bytearray()
    row_bytes = (LOGICAL_WIDTH + 7) // 8
    for row in logical:
        values = bytearray([0xFF] * row_bytes)
        for x, ink in enumerate(row):
            if ink:
                values[x // 8] &= ~(1 << (7 - (x % 8)))
        packed.extend(values)
    expected = row_bytes * LOGICAL_HEIGHT
    if len(packed) != expected:
        raise AssertionError(f"expected {expected} bytes, got {len(packed)}")
    return bytes(packed)


def c_bytes(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 12):
        values = ", ".join(f"0x{value:02x}" for value in data[offset : offset + 12])
        rows.append(f"    {values},")
    return "\n".join(rows)


def make_c_source(assets: list[tuple[str, str, bytes]]) -> bytes:
    declarations = []
    for symbol, label, pixels in assets:
        declarations.append(
            f'''/* {label}: physical 68x92, rotated clockwise to logical 92x68. */
static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t {symbol}_map[] = {{
#if CONFIG_NICE_VIEW_WIDGET_INVERTED
    0xff, 0xff, 0xff, 0xff, /* Color of index 0. */
    0x00, 0x00, 0x00, 0xff, /* Color of index 1. */
#else
    0x00, 0x00, 0x00, 0xff, /* Color of index 0. */
    0xff, 0xff, 0xff, 0xff, /* Color of index 1. */
#endif
{c_bytes(pixels)}
}};

const lv_img_dsc_t {symbol} = {{
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {LOGICAL_WIDTH},
    .header.h = {LOGICAL_HEIGHT},
    .data_size = sizeof({symbol}_map),
    .data = {symbol}_map,
}};'''
        )

    body = "\n\n".join(declarations)
    return f'''/*
 * Generated by tools/generate_rtr_art.py; do not edit by hand.
 * Five static images are stored in flash and selected one at a time.
 *
 * SPDX-License-Identifier: MIT
 */

#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

{body}
'''.encode("ascii")


def png_chunk(kind: bytes, data: bytes) -> bytes:
    return (
        struct.pack(">I", len(data))
        + kind
        + data
        + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)
    )


def make_preview_png(master: list[list[int]], scale: int = 4) -> bytes:
    width = PHYSICAL_WIDTH * scale
    height = PHYSICAL_HEIGHT * scale
    scanlines = []
    for row in master:
        expanded = bytes(0 if ink else 255 for ink in row for _ in range(scale))
        scanlines.extend([b"\x00" + expanded] * scale)
    header = struct.pack(">IIBBBBB", width, height, 8, 0, 0, 0, 0)
    return (
        b"\x89PNG\r\n\x1a\n"
        + png_chunk(b"IHDR", header)
        + png_chunk(b"IDAT", zlib.compress(b"".join(scanlines), 9))
        + png_chunk(b"IEND", b"")
    )


def expected_outputs() -> list[tuple[Path, bytes]]:
    assets = []
    outputs = []
    for symbol, label, encoded in SOURCES:
        master = decode_master(encoded)
        assets.append((symbol, label, pack_lvgl_rows(rotate_clockwise(master))))
        outputs.append((PREVIEW_DIR / f"{symbol}.png", make_preview_png(master)))
    outputs.append((ART_C_PATH, make_c_source(assets)))
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify generated files are current")
    args = parser.parse_args()
    outputs = expected_outputs()

    if args.check:
        stale = [
            str(path.relative_to(REPO_ROOT))
            for path, expected in outputs
            if not path.is_file() or path.read_bytes() != expected
        ]
        if stale:
            print("stale generated files: " + ", ".join(stale))
            return 1
        print("five-image RTR cycle outputs are current")
        return 0

    for path, data in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
